# Generated by Django 3.1.7 on 2021-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('describtion', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='image')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
